import { PRIMARY_COLOR } from '@/data/constants';
import type { CustomizationForm } from './_shared';

export const DEFAULT_CUSTOMIZATION: CustomizationForm = {
  site_color: PRIMARY_COLOR,
  site_color_secondary: '#cfe1b9',
  profile_bg_type: 'solid',
  profile_bg_color: '',
  profile_bg_gradient_end: '#ffffff',
  profile_bg_gradient_angle: 135,
  profile_bg_pattern: 'dots',
  profile_bg_image_size: 'cover',
  profile_bg_image_position: 'center center',
  profile_bg_image_fixed: false,
  profile_card_bg: '',
  profile_header_text_color: '',
  profile_font: '',
  profile_font_size: 'medium',
  profile_name_effect: 'none',
  profile_avatar_shape: 'circle',
  profile_cursor: 'default',
  profile_sparkles: false,
  profile_dark_mode: false,
  profile_mood_emoji: '',
  profile_mood_text: '',
  profile_youtube_url: '',
  social_links: [],
  tab_show_favorites: true,
  tab_show_done: true,
  tab_show_ratings: true,
  tab_show_difficulty: true,
  tab_show_gallery: true,
  tab_show_collections: true,
  header_gradient: true,
  blocked_tags: [],
  preferred_measurement_unit: 'original',
  featured_pattern_id: '',
  featured_pattern_note: '',
};
