/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceCommandIndexRouteImport } from './routes/space-command/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PatternPatternIdRouteImport } from './routes/pattern/$patternId'
import { Route as HelpTermsOfServiceRouteImport } from './routes/help/terms-of-service'
import { Route as HelpPrivacyPolicyRouteImport } from './routes/help/privacy-policy'
import { Route as HelpFaqRouteImport } from './routes/help/faq'
import { Route as HelpContactRouteImport } from './routes/help/contact'
import { Route as HelpAboutRouteImport } from './routes/help/about'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceCommandIndexRoute = SpaceCommandIndexRouteImport.update({
  id: '/space-command/',
  path: '/space-command/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternPatternIdRoute = PatternPatternIdRouteImport.update({
  id: '/pattern/$patternId',
  path: '/pattern/$patternId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTermsOfServiceRoute = HelpTermsOfServiceRouteImport.update({
  id: '/help/terms-of-service',
  path: '/help/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPrivacyPolicyRoute = HelpPrivacyPolicyRouteImport.update({
  id: '/help/privacy-policy',
  path: '/help/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/help/contact',
  path: '/help/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpAboutRoute = HelpAboutRouteImport.update({
  id: '/help/about',
  path: '/help/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/space-command/': typeof SpaceCommandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/collections': typeof CollectionsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/space-command': typeof SpaceCommandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/space-command/': typeof SpaceCommandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/collections/'
    | '/guides/'
    | '/profile/'
    | '/space-command/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/collections'
    | '/guides'
    | '/profile'
    | '/space-command'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/collections/'
    | '/guides/'
    | '/profile/'
    | '/space-command/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  HelpAboutRoute: typeof HelpAboutRoute
  HelpContactRoute: typeof HelpContactRoute
  HelpFaqRoute: typeof HelpFaqRoute
  HelpPrivacyPolicyRoute: typeof HelpPrivacyPolicyRoute
  HelpTermsOfServiceRoute: typeof HelpTermsOfServiceRoute
  PatternPatternIdRoute: typeof PatternPatternIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SpaceCommandIndexRoute: typeof SpaceCommandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space-command/': {
      id: '/space-command/'
      path: '/space-command'
      fullPath: '/space-command/'
      preLoaderRoute: typeof SpaceCommandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/$patternId': {
      id: '/pattern/$patternId'
      path: '/pattern/$patternId'
      fullPath: '/pattern/$patternId'
      preLoaderRoute: typeof PatternPatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/terms-of-service': {
      id: '/help/terms-of-service'
      path: '/help/terms-of-service'
      fullPath: '/help/terms-of-service'
      preLoaderRoute: typeof HelpTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/privacy-policy': {
      id: '/help/privacy-policy'
      path: '/help/privacy-policy'
      fullPath: '/help/privacy-policy'
      preLoaderRoute: typeof HelpPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/help/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/about': {
      id: '/help/about'
      path: '/help/about'
      fullPath: '/help/about'
      preLoaderRoute: typeof HelpAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  HelpAboutRoute: HelpAboutRoute,
  HelpContactRoute: HelpContactRoute,
  HelpFaqRoute: HelpFaqRoute,
  HelpPrivacyPolicyRoute: HelpPrivacyPolicyRoute,
  HelpTermsOfServiceRoute: HelpTermsOfServiceRoute,
  PatternPatternIdRoute: PatternPatternIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SpaceCommandIndexRoute: SpaceCommandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
