/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceCommandRouteRouteImport } from './routes/space-command/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceCommandIndexRouteImport } from './routes/space-command/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as SpaceCommandUsersRouteImport } from './routes/space-command/users'
import { Route as SpaceCommandTestRouteImport } from './routes/space-command/test'
import { Route as SpaceCommandTagsRouteImport } from './routes/space-command/tags'
import { Route as SpaceCommandPatternsRouteImport } from './routes/space-command/patterns'
import { Route as SpaceCommandMapRouteImport } from './routes/space-command/map'
import { Route as SpaceCommandFaqRouteImport } from './routes/space-command/faq'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PatternPatternIdRouteImport } from './routes/pattern/$patternId'
import { Route as HelpTermsOfServiceRouteImport } from './routes/help/terms-of-service'
import { Route as HelpPrivacyPolicyRouteImport } from './routes/help/privacy-policy'
import { Route as HelpFaqRouteImport } from './routes/help/faq'
import { Route as HelpContactRouteImport } from './routes/help/contact'
import { Route as HelpAboutRouteImport } from './routes/help/about'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SpaceCommandComplaintsIndexRouteImport } from './routes/space-command/complaints/index'
import { Route as SpaceCommandComplaintsReviewedRouteImport } from './routes/space-command/complaints/reviewed'

const SpaceCommandRouteRoute = SpaceCommandRouteRouteImport.update({
  id: '/space-command',
  path: '/space-command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceCommandIndexRoute = SpaceCommandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceCommandUsersRoute = SpaceCommandUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const SpaceCommandTestRoute = SpaceCommandTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const SpaceCommandTagsRoute = SpaceCommandTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const SpaceCommandPatternsRoute = SpaceCommandPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const SpaceCommandMapRoute = SpaceCommandMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const SpaceCommandFaqRoute = SpaceCommandFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SpaceCommandRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternPatternIdRoute = PatternPatternIdRouteImport.update({
  id: '/pattern/$patternId',
  path: '/pattern/$patternId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTermsOfServiceRoute = HelpTermsOfServiceRouteImport.update({
  id: '/help/terms-of-service',
  path: '/help/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPrivacyPolicyRoute = HelpPrivacyPolicyRouteImport.update({
  id: '/help/privacy-policy',
  path: '/help/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/help/contact',
  path: '/help/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpAboutRoute = HelpAboutRouteImport.update({
  id: '/help/about',
  path: '/help/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceCommandComplaintsIndexRoute =
  SpaceCommandComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => SpaceCommandRouteRoute,
  } as any)
const SpaceCommandComplaintsReviewedRoute =
  SpaceCommandComplaintsReviewedRouteImport.update({
    id: '/complaints/reviewed',
    path: '/complaints/reviewed',
    getParentRoute: () => SpaceCommandRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/space-command': typeof SpaceCommandRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/space-command/faq': typeof SpaceCommandFaqRoute
  '/space-command/map': typeof SpaceCommandMapRoute
  '/space-command/patterns': typeof SpaceCommandPatternsRoute
  '/space-command/tags': typeof SpaceCommandTagsRoute
  '/space-command/test': typeof SpaceCommandTestRoute
  '/space-command/users': typeof SpaceCommandUsersRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/space-command/': typeof SpaceCommandIndexRoute
  '/space-command/complaints/reviewed': typeof SpaceCommandComplaintsReviewedRoute
  '/space-command/complaints/': typeof SpaceCommandComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/space-command/faq': typeof SpaceCommandFaqRoute
  '/space-command/map': typeof SpaceCommandMapRoute
  '/space-command/patterns': typeof SpaceCommandPatternsRoute
  '/space-command/tags': typeof SpaceCommandTagsRoute
  '/space-command/test': typeof SpaceCommandTestRoute
  '/space-command/users': typeof SpaceCommandUsersRoute
  '/collections': typeof CollectionsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/space-command': typeof SpaceCommandIndexRoute
  '/space-command/complaints/reviewed': typeof SpaceCommandComplaintsReviewedRoute
  '/space-command/complaints': typeof SpaceCommandComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/space-command': typeof SpaceCommandRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/help/about': typeof HelpAboutRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/help/terms-of-service': typeof HelpTermsOfServiceRoute
  '/pattern/$patternId': typeof PatternPatternIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/space-command/faq': typeof SpaceCommandFaqRoute
  '/space-command/map': typeof SpaceCommandMapRoute
  '/space-command/patterns': typeof SpaceCommandPatternsRoute
  '/space-command/tags': typeof SpaceCommandTagsRoute
  '/space-command/test': typeof SpaceCommandTestRoute
  '/space-command/users': typeof SpaceCommandUsersRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/space-command/': typeof SpaceCommandIndexRoute
  '/space-command/complaints/reviewed': typeof SpaceCommandComplaintsReviewedRoute
  '/space-command/complaints/': typeof SpaceCommandComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/space-command'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/space-command/faq'
    | '/space-command/map'
    | '/space-command/patterns'
    | '/space-command/tags'
    | '/space-command/test'
    | '/space-command/users'
    | '/collections/'
    | '/guides/'
    | '/profile/'
    | '/space-command/'
    | '/space-command/complaints/reviewed'
    | '/space-command/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/space-command/faq'
    | '/space-command/map'
    | '/space-command/patterns'
    | '/space-command/tags'
    | '/space-command/test'
    | '/space-command/users'
    | '/collections'
    | '/guides'
    | '/profile'
    | '/space-command'
    | '/space-command/complaints/reviewed'
    | '/space-command/complaints'
  id:
    | '__root__'
    | '/'
    | '/space-command'
    | '/auth/login'
    | '/auth/register'
    | '/help/about'
    | '/help/contact'
    | '/help/faq'
    | '/help/privacy-policy'
    | '/help/terms-of-service'
    | '/pattern/$patternId'
    | '/profile/edit'
    | '/space-command/faq'
    | '/space-command/map'
    | '/space-command/patterns'
    | '/space-command/tags'
    | '/space-command/test'
    | '/space-command/users'
    | '/collections/'
    | '/guides/'
    | '/profile/'
    | '/space-command/'
    | '/space-command/complaints/reviewed'
    | '/space-command/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpaceCommandRouteRoute: typeof SpaceCommandRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  HelpAboutRoute: typeof HelpAboutRoute
  HelpContactRoute: typeof HelpContactRoute
  HelpFaqRoute: typeof HelpFaqRoute
  HelpPrivacyPolicyRoute: typeof HelpPrivacyPolicyRoute
  HelpTermsOfServiceRoute: typeof HelpTermsOfServiceRoute
  PatternPatternIdRoute: typeof PatternPatternIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space-command': {
      id: '/space-command'
      path: '/space-command'
      fullPath: '/space-command'
      preLoaderRoute: typeof SpaceCommandRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space-command/': {
      id: '/space-command/'
      path: '/'
      fullPath: '/space-command/'
      preLoaderRoute: typeof SpaceCommandIndexRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space-command/users': {
      id: '/space-command/users'
      path: '/users'
      fullPath: '/space-command/users'
      preLoaderRoute: typeof SpaceCommandUsersRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/test': {
      id: '/space-command/test'
      path: '/test'
      fullPath: '/space-command/test'
      preLoaderRoute: typeof SpaceCommandTestRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/tags': {
      id: '/space-command/tags'
      path: '/tags'
      fullPath: '/space-command/tags'
      preLoaderRoute: typeof SpaceCommandTagsRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/patterns': {
      id: '/space-command/patterns'
      path: '/patterns'
      fullPath: '/space-command/patterns'
      preLoaderRoute: typeof SpaceCommandPatternsRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/map': {
      id: '/space-command/map'
      path: '/map'
      fullPath: '/space-command/map'
      preLoaderRoute: typeof SpaceCommandMapRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/faq': {
      id: '/space-command/faq'
      path: '/faq'
      fullPath: '/space-command/faq'
      preLoaderRoute: typeof SpaceCommandFaqRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/$patternId': {
      id: '/pattern/$patternId'
      path: '/pattern/$patternId'
      fullPath: '/pattern/$patternId'
      preLoaderRoute: typeof PatternPatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/terms-of-service': {
      id: '/help/terms-of-service'
      path: '/help/terms-of-service'
      fullPath: '/help/terms-of-service'
      preLoaderRoute: typeof HelpTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/privacy-policy': {
      id: '/help/privacy-policy'
      path: '/help/privacy-policy'
      fullPath: '/help/privacy-policy'
      preLoaderRoute: typeof HelpPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/help/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/about': {
      id: '/help/about'
      path: '/help/about'
      fullPath: '/help/about'
      preLoaderRoute: typeof HelpAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space-command/complaints/': {
      id: '/space-command/complaints/'
      path: '/complaints'
      fullPath: '/space-command/complaints/'
      preLoaderRoute: typeof SpaceCommandComplaintsIndexRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
    '/space-command/complaints/reviewed': {
      id: '/space-command/complaints/reviewed'
      path: '/complaints/reviewed'
      fullPath: '/space-command/complaints/reviewed'
      preLoaderRoute: typeof SpaceCommandComplaintsReviewedRouteImport
      parentRoute: typeof SpaceCommandRouteRoute
    }
  }
}

interface SpaceCommandRouteRouteChildren {
  SpaceCommandFaqRoute: typeof SpaceCommandFaqRoute
  SpaceCommandMapRoute: typeof SpaceCommandMapRoute
  SpaceCommandPatternsRoute: typeof SpaceCommandPatternsRoute
  SpaceCommandTagsRoute: typeof SpaceCommandTagsRoute
  SpaceCommandTestRoute: typeof SpaceCommandTestRoute
  SpaceCommandUsersRoute: typeof SpaceCommandUsersRoute
  SpaceCommandIndexRoute: typeof SpaceCommandIndexRoute
  SpaceCommandComplaintsReviewedRoute: typeof SpaceCommandComplaintsReviewedRoute
  SpaceCommandComplaintsIndexRoute: typeof SpaceCommandComplaintsIndexRoute
}

const SpaceCommandRouteRouteChildren: SpaceCommandRouteRouteChildren = {
  SpaceCommandFaqRoute: SpaceCommandFaqRoute,
  SpaceCommandMapRoute: SpaceCommandMapRoute,
  SpaceCommandPatternsRoute: SpaceCommandPatternsRoute,
  SpaceCommandTagsRoute: SpaceCommandTagsRoute,
  SpaceCommandTestRoute: SpaceCommandTestRoute,
  SpaceCommandUsersRoute: SpaceCommandUsersRoute,
  SpaceCommandIndexRoute: SpaceCommandIndexRoute,
  SpaceCommandComplaintsReviewedRoute: SpaceCommandComplaintsReviewedRoute,
  SpaceCommandComplaintsIndexRoute: SpaceCommandComplaintsIndexRoute,
}

const SpaceCommandRouteRouteWithChildren =
  SpaceCommandRouteRoute._addFileChildren(SpaceCommandRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpaceCommandRouteRoute: SpaceCommandRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  HelpAboutRoute: HelpAboutRoute,
  HelpContactRoute: HelpContactRoute,
  HelpFaqRoute: HelpFaqRoute,
  HelpPrivacyPolicyRoute: HelpPrivacyPolicyRoute,
  HelpTermsOfServiceRoute: HelpTermsOfServiceRoute,
  PatternPatternIdRoute: PatternPatternIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
